version: '3.3'

services:
  
  rabbitmq:
    image: 'rabbitmq:3.6-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'

    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:15672"]
        interval: 60s
        timeout: 10s
        retries: 10
        
    networks:
      - network

  reader:
    build: reader

    environment:
      USERNAME: 'username'
      PASSWORD: 'password'

    restart: on-failure

    depends_on:
      - rabbitmq
    links: 
        - rabbitmq

    networks:
      - network


  writer:
    build: writer

    environment:
      AUSERNAME: 'username'
      PASSWORD: 'password'

    restart: on-failure
    depends_on:
      - rabbitmq
    links: 
        - rabbitmq

    networks:
      - network

  postgres:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "5432:5432"


networks:
  network: {}